# Auto-generated from mapping_proposal.md
FEATURE_MAPPINGS = {
    1: {'name': 'Vessel Call Sign', 'section': 'VESSEL/TRANSPORT IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'VESSEL_CALL_SIGN'), ('OTHER_ID_NUMBER', None)]},
    2: {'name': 'VESSEL TYPE', 'section': 'DESCRIPTIVE ATTRIBUTES (Payload - Non-matching)', 'instructions': [('VESSEL_TYPE', None)]},
    3: {'name': 'Vessel Flag', 'section': 'VESSEL/TRANSPORT IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'VESSEL_FLAG'), ('OTHER_ID_NUMBER', None)]},
    4: {'name': 'Vessel Owner', 'section': 'DESCRIPTIVE ATTRIBUTES (Payload - Non-matching)', 'instructions': [('VESSEL_OWNER', None)]},
    5: {'name': 'Vessel Tonnage', 'section': 'DESCRIPTIVE ATTRIBUTES (Payload - Non-matching)', 'instructions': [('VESSEL_TONNAGE', None)]},
    6: {'name': 'Vessel Gross Registered Tonnage', 'section': 'DESCRIPTIVE ATTRIBUTES (Payload - Non-matching)', 'instructions': [('VESSEL_GRT', None)]},
    8: {'name': 'Birthdate', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('DATE_OF_BIRTH', None)]},
    9: {'name': 'Place of Birth', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('PLACE_OF_BIRTH', None)]},
    10: {'name': 'Nationality Country', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('NATIONALITY', None)]},
    11: {'name': 'Citizenship Country', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('CITIZENSHIP', None)]},
    13: {'name': 'SWIFT/BIC', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('OTHER_ID_TYPE', 'SWIFT'), ('OTHER_ID_NUMBER', None)]},
    14: {'name': 'Website', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('WEBSITE_ADDRESS', None)]},
    21: {'name': 'Email Address', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('EMAIL_ADDRESS', None)]},
    24: {'name': 'Former Vessel Flag', 'section': 'VESSEL/TRANSPORT IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'FORMER_VESSEL_FLAG'), ('OTHER_ID_NUMBER', None)]},
    25: {'name': 'Location', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('ADDR_FULL', None)]},
    26: {'name': 'Title', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('NAME_PREFIX', None)]},
    44: {'name': 'Aircraft Construction Number', 'section': 'VESSEL/TRANSPORT IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'AIRCRAFT_CONSTRUCTION'), ('OTHER_ID_NUMBER', None)]},
    45: {'name': 'Aircraft Manufacture Date', 'section': 'DESCRIPTIVE ATTRIBUTES (Payload - Non-matching)', 'instructions': [('AIRCRAFT_MANUFACTURE_DATE', None)]},
    46: {'name': 'Aircraft Mode S Transponder Code', 'section': 'VESSEL/TRANSPORT IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'TRANSPONDER'), ('OTHER_ID_NUMBER', None)]},
    47: {'name': 'Aircraft Model', 'section': 'DESCRIPTIVE ATTRIBUTES (Payload - Non-matching)', 'instructions': [('AIRCRAFT_MODEL', None)]},
    48: {'name': 'Aircraft Operator', 'section': 'DESCRIPTIVE ATTRIBUTES (Payload - Non-matching)', 'instructions': [('AIRCRAFT_OPERATOR', None)]},
    49: {'name': 'Previous Aircraft Tail Number', 'section': 'VESSEL/TRANSPORT IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'PREV_AIRCRAFT_TAIL'), ('OTHER_ID_NUMBER', None)]},
    50: {'name': "Aircraft Manufacturer's Serial Number", 'section': 'VESSEL/TRANSPORT IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'AIRCRAFT_MSN'), ('OTHER_ID_NUMBER', None)]},
    64: {'name': 'Aircraft Tail Number', 'section': 'VESSEL/TRANSPORT IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'AIRCRAFT_TAIL'), ('OTHER_ID_NUMBER', None)]},
    104: {'name': 'IFCA Determination', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('IFCA_DETERMINATION', None)]},
    125: {'name': 'Additional Sanctions Information', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('SANCTIONS_INFO', None)]},
    164: {'name': 'BIK (RU)', 'section': 'FINANCIAL/MARKET IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'BIK'), ('OTHER_ID_NUMBER', None)]},
    204: {'name': 'Executive Order 13662 Directive', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('EO_13662_DIRECTIVE', None)]},
    224: {'name': 'Gender', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('GENDER', None)]},
    264: {'name': 'UN/LOCODE', 'section': 'FINANCIAL/MARKET IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'LOCODE'), ('OTHER_ID_NUMBER', None)]},
    304: {'name': 'MICEX Code', 'section': 'FINANCIAL/MARKET IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'MICEX'), ('OTHER_ID_NUMBER', None)]},
    344: {'name': 'Digital Currency Address - XBT', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_XBT'), ('OTHER_ID_NUMBER', None)]},
    345: {'name': 'Digital Currency Address - ETH', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_ETH'), ('OTHER_ID_NUMBER', None)]},
    364: {'name': 'D-U-N-S Number', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('DUNS_NUMBER', None)]},
    365: {'name': 'Nationality of Registration', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('REGISTRATION_COUNTRY', None)]},
    404: {'name': 'Registration Country', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('REGISTRATION_COUNTRY', None)]},
    424: {'name': 'Other Vessel Flag', 'section': 'VESSEL/TRANSPORT IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'OTHER_VESSEL_FLAG'), ('OTHER_ID_NUMBER', None)]},
    425: {'name': 'Other Vessel Call Sign', 'section': 'VESSEL/TRANSPORT IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'OTHER_CALL_SIGN'), ('OTHER_ID_NUMBER', None)]},
    444: {'name': 'Digital Currency Address - XMR', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_XMR'), ('OTHER_ID_NUMBER', None)]},
    504: {'name': 'Secondary sanctions risk', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('SECONDARY_SANCTIONS_RISK', None)]},
    524: {'name': 'Phone Number', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('PHONE_NUMBER', None)]},
    525: {'name': 'CAATSA Section 235 Information', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('CAATSA_235_INFO', None)]},
    526: {'name': 'Other Vessel Type', 'section': 'DESCRIPTIVE ATTRIBUTES (Payload - Non-matching)', 'instructions': [('OTHER_VESSEL_TYPE', None)]},
    566: {'name': 'Digital Currency Address - LTC', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_LTC'), ('OTHER_ID_NUMBER', None)]},
    586: {'name': 'Executive Order 13846 information', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('EO_13846_INFO', None)]},
    626: {'name': 'Transactions Prohibited For Persons Owned or Controlled By U.S. Financial Institutions', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('US_FI_PROHIBITION', None)]},
    646: {'name': 'Organization Established Date', 'section': 'DIRECT SENZING MAPPINGS (High Confidence)', 'instructions': [('REGISTRATION_DATE', None)]},
    647: {'name': 'Organization Type', 'section': 'DESCRIPTIVE ATTRIBUTES (Payload - Non-matching)', 'instructions': [('ORGANIZATION_TYPE', None)]},
    686: {'name': 'Digital Currency Address - ZEC', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_ZEC'), ('OTHER_ID_NUMBER', None)]},
    687: {'name': 'Digital Currency Address - DASH', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_DASH'), ('OTHER_ID_NUMBER', None)]},
    688: {'name': 'Digital Currency Address - BTG', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_BTG'), ('OTHER_ID_NUMBER', None)]},
    689: {'name': 'Digital Currency Address - ETC', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_ETC'), ('OTHER_ID_NUMBER', None)]},
    706: {'name': 'Digital Currency Address - BSV', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_BSV'), ('OTHER_ID_NUMBER', None)]},
    726: {'name': 'Digital Currency Address - BCH', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_BCH'), ('OTHER_ID_NUMBER', None)]},
    746: {'name': 'Digital Currency Address - XVG', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_XVG'), ('OTHER_ID_NUMBER', None)]},
    766: {'name': 'Equity Ticker', 'section': 'FINANCIAL/MARKET IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'EQUITY_TICKER'), ('OTHER_ID_NUMBER', None)]},
    806: {'name': 'ISIN', 'section': 'FINANCIAL/MARKET IDENTIFIERS (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'ISIN'), ('OTHER_ID_NUMBER', None)]},
    826: {'name': 'Target Type', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('TARGET_TYPE', None)]},
    827: {'name': 'PEESA Information', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('PEESA_INFO', None)]},
    887: {'name': 'Digital Currency Address - USDT', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_USDT'), ('OTHER_ID_NUMBER', None)]},
    907: {'name': 'Digital Currency Address - XRP', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_XRP'), ('OTHER_ID_NUMBER', None)]},
    947: {'name': 'Executive Order 14024 Directive Information', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('EO_14024_DIRECTIVE', None)]},
    948: {'name': 'Executive Order 14024 Directive Information', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('EO_14024_DIRECTIVE_ALT', None)]},
    951: {'name': 'Listing Date (EO 14024 Directive 2)', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('EO_14024_D2_LISTING_DATE', None)]},
    952: {'name': 'Effective Date (EO 14024 Directive 2)', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('EO_14024_D2_EFFECTIVE_DATE', None)]},
    953: {'name': 'Listing Date (EO 14024 Directive 3)', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('EO_14024_D3_LISTING_DATE', None)]},
    954: {'name': 'Effective Date (EO 14024 Directive 3)', 'section': 'PAYLOAD ATTRIBUTES (Root Level - Sanctions Specific)', 'instructions': [('EO_14024_D3_EFFECTIVE_DATE', None)]},
    967: {'name': 'Vessel Year of Build', 'section': 'DESCRIPTIVE ATTRIBUTES (Payload - Non-matching)', 'instructions': [('VESSEL_BUILD_YEAR', None)]},
    992: {'name': 'Digital Currency Address - TRX', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_TRX'), ('OTHER_ID_NUMBER', None)]},
    998: {'name': 'Digital Currency Address - USDC', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_USDC'), ('OTHER_ID_NUMBER', None)]},
    1007: {'name': 'Digital Currency Address - ARB', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_ARB'), ('OTHER_ID_NUMBER', None)]},
    1008: {'name': 'Digital Currency Address - BSC', 'section': 'CRYPTOCURRENCY ADDRESSES (OTHER_ID Mapping)', 'instructions': [('OTHER_ID_TYPE', 'CRYPTO_BSC'), ('OTHER_ID_NUMBER', None)]},
}
